package api

import("context";"errors";"math/big";"strconv";"strings";"github.com/Josemilk/wallet-core/exchange/backend/internal/db";"github.com/Josemilk/wallet-core/exchange/backend/internal/marketdata";"github.com/jackc/pgx/v5")

type PostgresDashboardSource struct{DB *db.DB;Market marketdata.Provider;AssetIDs []string}
func(s *PostgresDashboardSource)Portfolio(ctx context.Context,userID string)(Portfolio,error){if s==nil||s.DB==nil||s.DB.Pool==nil||s.Market==nil{return Portfolio{},errors.New("dashboard source unavailable")};quotes,err:=s.Market.Quotes(ctx,s.AssetIDs,"USD");if err!=nil{return Portfolio{},err};prices:=map[string]float64{};for _,q:=range quotes{prices[strings.ToUpper(q.Symbol)]=q.Price};rows,err:=s.DB.Pool.Query(ctx,`SELECT a.asset,b.available+b.locked,COALESCE(am.decimals,8) FROM accounts a JOIN balances b ON b.account_id=a.id AND b.asset=a.asset LEFT JOIN asset_metadata am ON am.asset=a.asset WHERE a.user_id=$1 AND a.kind='AVAILABLE'`,userID);if err!=nil{return Portfolio{},err};defer rows.Close();total:=new(big.Float).SetPrec(256);for rows.Next(){var asset,raw string;var decimals int;if err:=rows.Scan(&asset,&raw,&decimals);err!=nil{return Portfolio{},err};price,ok:=prices[strings.ToUpper(asset)];if !ok{continue};units:=new(big.Float);if _,ok:=units.SetString(raw);!ok{continue};den:=new(big.Float).SetFloat64(float64Pow10(decimals));units.Quo(units,den);units.Mul(units,new(big.Float).SetFloat64(price));total.Add(total,units)};if err:=rows.Err();err!=nil{return Portfolio{},err};return Portfolio{TotalUSD:formatUSD(total),InvestedUSD:"0.00",ProfitUSD:"0.00",DayPnLUSD:"0.00"},nil}
func(s *PostgresDashboardSource)Events(ctx context.Context,userID string)([]EventSummary,error){if s==nil||s.DB==nil||s.DB.Pool==nil{return nil,errors.New("dashboard source unavailable")};rows,err:=s.DB.Pool.Query(ctx,`SELECT e.id::text,e.title,e.event_type,e.entry_price::text,e.prize_amount::text,e.starts_at::text,e.ends_at::text FROM events e WHERE e.status IN ('scheduled','open','locked') AND e.starts_at<=now()+interval '30 days' ORDER BY e.sort_order,e.starts_at`);if err!=nil{return nil,err};defer rows.Close();out:=[]EventSummary{};for rows.Next(){var x EventSummary;if err:=rows.Scan(&x.ID,&x.Title,&x.Type,&x.EntryPrice,&x.Prize,&x.StartsAt,&x.EndsAt);err!=nil{return nil,err};out=append(out,x)};return out,rows.Err()}
func formatUSD(v *big.Float)string{f,_:=v.Float64();return strconv.FormatFloat(f,'f',2,64)}
func float64Pow10(n int)float64{if n<0||n>18{return 1};v:=1.0;for i:=0;i<n;i++{v*=10};return v}
var _ pgx.Row
