package blockchain

import("context";"encoding/hex";"errors";"fmt";"math/big";"strconv";"strings")
const ERC20TransferTopic="0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
type ObservedDeposit struct{Network,TxHash,BlockHash,Address,Asset,ContractAddress,Amount string;BlockHeight,Confirmations uint64}
type DepositSink interface{Observe(context.Context,ObservedDeposit)error}

type BitcoinDepositScanner struct{RPC *BitcoinRPC;Watched map[string]string;Network string}
func(s *BitcoinDepositScanner)ScanBlock(ctx context.Context,height,tipHeight uint64,sink DepositSink)error{if s==nil||s.RPC==nil||sink==nil{return errors.New("bitcoin scanner dependencies missing")};if len(s.Watched)==0{return nil};hash,err:=s.RPC.BlockHash(ctx,height);if err!=nil{return err};b,err:=s.RPC.Block(ctx,hash);if err!=nil{return err};txs,_:=b["tx"].([]any);conf:=tipHeight-height+1;for _,raw:=range txs{tx,ok:=raw.(map[string]any);if !ok{continue};txHash,_:=tx["txid"].(string);vouts,ok:=tx["vout"].([]any);if !ok{continue};for _,rv:=range vouts{vout,ok:=rv.(map[string]any);if !ok{continue};spk,_:=vout["scriptPubKey"].(map[string]any);addresses:=[]string{};if a,ok:=spk["address"].(string);ok{addresses=append(addresses,a)};if aa,ok:=spk["addresses"].([]any);ok{for _,x:=range aa{if a,ok:=x.(string);ok{addresses=append(addresses,a)}}};value,ok:=vout["value"].(float64);if !ok||value<=0{continue};amount,err:=decimalUnits(strconv.FormatFloat(value,'f',8,64),8);if err!=nil{continue};for _,address:=range addresses{asset,watched:=s.Watched[address];if !watched{continue};if err:=sink.Observe(ctx,ObservedDeposit{Network:s.Network,TxHash:txHash,BlockHash:hash,Address:address,Asset:asset,Amount:amount,BlockHeight:height,Confirmations:conf});err!=nil{return err}}}}};return nil}

type EVMNativeDepositScanner struct{RPC *EVMRPC;Network,Asset string;Watched map[string]bool;Decimals int}
func(s *EVMNativeDepositScanner)ScanRange(ctx context.Context,from,to uint64,sink DepositSink)error{if s==nil||s.RPC==nil||sink==nil{return errors.New("EVM native scanner dependencies missing")};if s.Asset==""{return errors.New("EVM native asset required")};for h:=from;h<=to;h++{b,err:=s.RPC.BlockByNumber(ctx,h);if err!=nil{return err};hash,_:=b["hash"].(string);txs,_:=b["transactions"].([]any);for _,raw:=range txs{tx,ok:=raw.(map[string]any);if !ok{continue};toAddr,_:=tx["to"].(string);toAddr=strings.ToLower(toAddr);if !s.Watched[toAddr]{continue};value,_:=tx["value"].(string);amount,err:=hexQuantityDecimal(value);if err!=nil||amount=="0"{continue};txHash,_:=tx["hash"].(string);if err:=sink.Observe(ctx,ObservedDeposit{Network:s.Network,TxHash:txHash,BlockHash:hash,Address:toAddr,Asset:s.Asset,Amount:amount,BlockHeight:h,Confirmations:to-h+1});err!=nil{return err}}};return nil}

type EVMERC20DepositScanner struct{RPC *EVMRPC;Network string;ContractAssets map[string]string;Watched map[string]string}
func(s *EVMERC20DepositScanner)ScanRange(ctx context.Context,from,to uint64,sink DepositSink)error{if s==nil||s.RPC==nil||sink==nil{return errors.New("EVM scanner dependencies missing")};if len(s.Watched)==0||len(s.ContractAssets)==0{return nil};contracts:=make([]string,0,len(s.ContractAssets));for c:=range s.ContractAssets{contracts=append(contracts,c)};for _,contract:=range contracts{logs,err:=s.RPC.Logs(ctx,from,to,contract,[]string{ERC20TransferTopic});if err!=nil{return err};for _,l:=range logs{topics,_:=l["topics"].([]any);if len(topics)<3{continue};toTopic,_:=topics[2].(string);address,ok:=topicAddress(toTopic);if !ok{continue};asset,watched:=s.Watched[strings.ToLower(address)];if !watched{continue};contractAsset:=s.ContractAssets[contract];data,_:=l["data"].(string);amount,err:=hexQuantityDecimal(data);if err!=nil||amount=="0"{continue};bh,err:=parseHexUint(fmt.Sprint(l["blockNumber"]));if err!=nil||bh>to{continue};blockHash,_:=l["blockHash"].(string);txHash,_:=l["transactionHash"].(string);if err:=sink.Observe(ctx,ObservedDeposit{Network:s.Network,TxHash:txHash,BlockHash:blockHash,Address:address,Asset:asset,ContractAddress:contractAsset,Amount:amount,BlockHeight:bh,Confirmations:to-bh+1});err!=nil{return err}}};return nil}
func topicAddress(topic string)(string,bool){t:=strings.TrimPrefix(strings.ToLower(topic),"0x");if len(t)!=64{return "",false};b,err:=hex.DecodeString(t);if err!=nil{return "",false};return "0x"+hex.EncodeToString(b[12:]),true}
func hexQuantityDecimal(v string)(string,error){v=strings.TrimPrefix(v,"0x");if v==""{return "0",nil};if _,err:=hex.DecodeString(func()string{if len(v)%2==1{return "0"+v};return v}());err!=nil{return "",err};n:=new(big.Int);if _,ok:=n.SetString(v,16);!ok{return "",errors.New("invalid EVM quantity")};return n.String(),nil}
func decimalUnits(v string,decimals int)(string,error){if decimals<0||decimals>38{return "",errors.New("invalid decimals")};parts:=strings.Split(v,".");if len(parts)>2{return "",errors.New("invalid decimal")};whole:=parts[0];frac:="";if len(parts)==2{frac=parts[1]};if len(frac)>decimals{frac=frac[:decimals]};frac+=strings.Repeat("0",decimals-len(frac));n:=new(big.Int);if _,ok:=n.SetString(strings.TrimPrefix(whole,"+"),10);!ok{return "",errors.New("invalid decimal whole")};scale:=new(big.Int).Exp(big.NewInt(10),big.NewInt(int64(decimals)),nil);n.Mul(n,scale);if frac!=""{f:=new(big.Int);if _,ok:=f.SetString(frac,10);!ok{return "",errors.New("invalid decimal fraction")};n.Add(n,f)};return n.String(),nil}
