package txcodec

import("context";"encoding/hex";"encoding/json";"errors";"math/big";"strings")

type EVM1559SigningEnvelope struct{ChainID string `json:"chainId"`;Nonce string `json:"nonce"`;MaxPriorityFeePerGas string `json:"maxPriorityFeePerGas"`;MaxFeePerGas string `json:"maxFeePerGas"`;GasLimit string `json:"gasLimit"`;To string `json:"to"`;Value string `json:"value"`;Data string `json:"data"`;AccessList []EVMAccessEnvelope `json:"accessList"`}
type EVMAccessEnvelope struct{Address string `json:"address"`;StorageKeys []string `json:"storageKeys"`}

type EVM1559Assembler struct{}
func(a EVM1559Assembler)Assemble(ctx context.Context,network,rawTransaction string,derSignature,publicKeyPEM []byte)(string,error){_ = ctx;if !strings.HasPrefix(strings.ToLower(network),"evm"){return "",errors.New("EVM assembler received non-EVM network")};var e EVM1559SigningEnvelope;if err:=json.Unmarshal([]byte(rawTransaction),&e);err!=nil{return "",errors.New("EVM signing envelope must be canonical JSON")};tx,err:=e.toTx();if err!=nil{return "",err};digest,err:=EIP1559Digest(tx);if err!=nil{return "",err};if !verifyDigest(publicKeyPEM,digest,derSignature){return "",errors.New("KMS signature does not verify against transaction digest")};rec,err:=recoveryID(digest,derSignature,publicKeyPEM);if err!=nil{return "",err};sig,err:=parseECDSADER(derSignature);if err!=nil{return "",err};r:=intBytes(sig.R);s:=intBytes(sig.S);items:=[][]byte{intBytes(tx.ChainID),intBytes(tx.Nonce),intBytes(tx.MaxPriorityFeePerGas),intBytes(tx.MaxFeePerGas),intBytes(tx.GasLimit),tx.To,intBytes(tx.Value),tx.Data,encodeAccessList(tx.AccessList),[]byte{byte(rec)},r,s};return "0x"+hex.EncodeToString(append([]byte{0x02},rlpListRaw(items)...)),nil}
func(e EVM1559SigningEnvelope)toTx()(EVM1559Tx,error){vals:=[]*big.Int{new(big.Int),new(big.Int),new(big.Int),new(big.Int),new(big.Int),new(big.Int)};src:=[]string{e.ChainID,e.Nonce,e.MaxPriorityFeePerGas,e.MaxFeePerGas,e.GasLimit,e.Value};for i,s:=range src{if s==""{return EVM1559Tx{},errors.New("missing EIP-1559 numeric field")};if _,ok:=vals[i].SetString(strings.TrimPrefix(s,"0x"),16);!ok{return EVM1559Tx{},errors.New("invalid EIP-1559 numeric field")}};to:=[]byte(nil);if e.To!=""{var err error;to,err=decodeHexFixed(e.To,20);if err!=nil{return EVM1559Tx{},err}};data,err:=decodeHex(e.Data);if err!=nil{return EVM1559Tx{},err};al:=make([]AccessTuple,0,len(e.AccessList));for _,a:=range e.AccessList{addr,err:=decodeHexFixed(a.Address,20);if err!=nil{return EVM1559Tx{},err};keys:=make([][]byte,0,len(a.StorageKeys));for _,k:=range a.StorageKeys{v,err:=decodeHexFixed(k,32);if err!=nil{return EVM1559Tx{},err};keys=append(keys,v)};al=append(al,AccessTuple{Address:addr,StorageKeys:keys})};return EVM1559Tx{ChainID:vals[0],Nonce:vals[1],MaxPriorityFeePerGas:vals[2],MaxFeePerGas:vals[3],GasLimit:vals[4],To:to,Value:vals[5],Data:data,AccessList:al},nil}
func decodeHex(s string)([]byte,error){s=strings.TrimPrefix(strings.TrimPrefix(s,"0x"),"0X");if s==""{return nil,nil};if len(s)%2!=0{return nil,errors.New("odd-length hex")};return hex.DecodeString(s)}
func decodeHexFixed(s string,n int)([]byte,error){b,err:=decodeHex(s);if err!=nil{return nil,err};if len(b)!=n{return nil,errors.New("invalid fixed-width hex")};return b,nil}
